"""setup

Revision ID: e37c6e088669
Revises: 
Create Date: 2020-04-15 02:57:53.706183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e37c6e088669'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extensions',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('isLoaded', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('extensions')
    # ### end Alembic commands ###
